M48
; DRILL file {KiCad 7.0.1} date Mon Apr  3 10:55:15 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-03T10:55:15-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0480
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0559
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0563
%
G90
G05
T1
X1.03Y-4.2124
X1.3966Y-4.8293
X1.76Y-4.2024
T2
X1.03Y-4.3345
X1.3966Y-4.9513
X1.76Y-4.3245
T3
X1.03Y-4.6613
X1.3966Y-5.2781
X1.76Y-4.6513
T0
M30
